---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - bridge_network
                - download_tls_cert_and_key
                - dependency
                - install
                - install2
                - local_volume_from_device
                - prune
                - swarm_worker_node
          required:
            - command
        instance: "{{ docker }}"

    - include_tasks: '{{ docker.command }}.yml'
  tags:
    - docker
