---

- block:
    - validate:
        schema:
          type: object
          properties:
            cert_url:
              type: string
              format: uri
            key_url:
              type: string
              format: uri
          required:
            - cert_url
            - key_url
        instance: "{{ docker }}"
      register: docker_validated

    - set_fact:
        docker_v: "{{ docker_validated.result }}"

    - block:
        - name: "Create /etc/docker"
          file:
            path: /etc/docker
            state: directory

        - name: "Download Docker TLS certificate"
          get_url:
            url: "{{ docker_v.cert_url }}"
            dest: /etc/docker/tls_cert.pem
            force: yes

        - name: "Download Docker TLS key"
          get_url:
            url: "{{ docker_v.key_url }}"
            dest: /etc/docker/tls_key.pem
            force: yes
      become: yes
  tags:
    - docker_download_tls_cert_and_key
