---

- validate:
    schema:
      type: object
      properties:
        tls_cert_url:
          type: string
          format: uri
        tls_key_url:
          type: string
          format: uri
      required:
        - tls_cert_url
        - tls_key_url
    instance: "{{ docker }}"
  register: docker_validated

- set_fact:
    docker_v: "{{ docker_validated.result }}"

- block:
    - name: "Create /etc/docker"
      file:
        path: /etc/docker
        state: directory

    - name: "Download Docker TLS certificate"
      get_url:
        url: "{{ docker_v.tls_cert_url }}"
        dest: /etc/docker/tls_cert.pem
        force: yes

    - name: "Download Docker TLS key"
      get_url:
        url: "{{ docker_v.tls_key_url }}"
        dest: /etc/docker/tls_key.pem
        force: yes
  become: yes