---

- validate:
    schema:
      type: object
      properties:
        build:
          type: string
          default: stable
          enum:
            - stable
            - edge
        tls:
          type: boolean
          default: yes
        uninstall_previous_versions:
          type: boolean
          default: true
        user:
          type: string
          default: ubuntu
      required:
        - build
        - tls
        - uninstall_previous_versions
        - user
    instance: "{{ docker }}"
  register: docker_validated

- set_fact:
    docker_v: "{{ docker_validated.result }}"

- block:
    - name: "Install Docker and Compose"
      import_role:
        name: angstwad.docker_ubuntu
      vars:
        daemon_json:
          iptables: yes
          ip-forward: yes
          tls: "{{ docker_v.tls }}"
          tlscert: "{{ docker_v.tls | ternary('/etc/docker/tls_cert.pem', None) }}"
          tlskey: "{{ docker_v.tls | ternary('/etc/docker/tls_key.pem', None) }}"
          hosts:
            - tcp://0.0.0.0:2376
            - unix:///var/run/docker.sock
        docker_apt_channel: "{{ docker_v.build }}"
        docker_group_members: "{{ docker_v.user }}"
        uninstall_previous_docker_versions: "{{ docker_v.uninstall_previous_versions }}"

    - name: "Enable ip forwarding in the kernel"
      lineinfile:
        path: /etc/sysctl.conf
        regexp: net.ipv4.ip_forward
        line: net.ipv4.ip_forward=1
      notify: sysctl_reload

    - name: "Enabling memory accounting"
      lineinfile:
        path: /etc/default/grub
        regexp: GRUB_CMDLINE_LINUX_DEFAULT
        line: GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"
      notify:
        - grub_update
        - reboot
  become: yes

- name: "Reset the ssh connection to pick up docker group membership"
  import_role:
    name: jcheroske.common
  vars:
    common:
      command: controller_reset_connection
