---

- block:
    - validate:
        schema:
          type: object
          properties:
            build:
              type: string
              enum:
                - stable
                - edge
              default: stable
            edition:
              type: string
              enum:
                - ce
                - ee
              default: ce
            install_compose:
              type: boolean
              default: false
            manipulate_iptables:
              type: boolean
              default: true
            tls_cert_path:
              type: string
              default: /etc/docker/tls_cert.pem
            tls_enable:
              type: boolean
              default: true
            tls_key_path:
              type: string
              default: /etc/docker/tls_key.pem
            user:
              type: string
              default: ubuntu
          required:
            - build
            - edition
            - install_compose
            - manipulate_iptables
            - tls_cert_path
            - tls_enable
            - tls_key_path
            - user
        instance: "{{ docker }}"
      register: docker_validated

    - set_fact:
        docker_v: "{{ docker_validated.result }}"

    - block:
        - name: "Install Docker"
          import_role:
            name: angstwad.docker_ubuntu
          vars:
            daemon_json:
              iptables: "{{ docker_v.manipulate_iptables }}"
              ip-forward: yes
              tls: "{{ docker_v.tls_enable }}"
              tlscert: "{{ docker_v.tls_enable | ternary(docker_v.tls_cert_path, None) }}"
              tlskey: "{{ docker_v.tls_enable | ternary(docker_v.tls_key_path, None) }}"
              tlsverify: "{{ docker_v.tls_enable | ternary(true, None) }}"
              hosts:
                - "tcp://0.0.0.0:{{ docker_v.tls_enable | ternary('2376', '2375') }}"
                - fd://
            docker_apt_channel: "{{ docker_v.build }}"
            docker_edition: "{{ docker_v.edition }}"
            docker_group_members: "{{ docker_v.user }}"
            pip_install_docker_compose: "{{ docker_v.install_compose }}"
            uninstall_previous_docker_versions: true

        - name: "Enable ip forwarding in the kernel"
          sysctl:
            name: net.ipv4.ip_forward
            value: 1
            sysctl_set: yes
            state: present
            reload: yes

        - name: "Enable memory and swap accounting"
          lineinfile:
            path: /etc/default/grub
            regexp: GRUB_CMDLINE_LINUX_DEFAULT
            line: GRUB_CMDLINE_LINUX_DEFAULT="cgroup_enable=memory swapaccount=1"
          notify:
            - grub_update
            - reboot
      become: yes

    - name: "Reset the ssh connection to pick up docker group membership"
      import_role:
        name: bedrock.common
      vars:
        common:
          command: controller_reset_connection
  tags:
    - docker_install