---

- validate:
    schema:
      type: object
      properties:
        device:
          type: string
        name:
          type: string
        state:
          type: string
          enum:
            - absent
            - present
          default: present
      required:
        - device
        - name
        - state
    instance: "{{ docker }}"
  register: docker_validated

- set_fact:
    docker_v: "{{ docker_validated.result }}"

- name: "Format device {{ docker_v.device }}"
  filesystem:
    fstype: ext4
    dev: "{{ docker_v.device }}"
    opts: -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard
  become: yes
  when: docker_v.state == 'present'

- name: "Mange volume {{ docker_v.name }} on device {{ docker_v.device }}: {{ docker_v.state }}"
  docker_volume:
    driver: local
    driver_options:
      device: "{{ docker_v.device }}"
      type: "{{ docker_v.filesystem }}"
    state: "{{ docker_v.state }}"
    volume_name: "{{ docker_v.name }}"
