---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - bridge_network
                - install
                - prune_images
                - swarm
        instance: "{{ docker }}"

    - include_tasks: '{{ docker.command }}.yml'
  when: not dependency