---

- debug:
    var: docker

- validate:
    schema:
      type: object
      properties:
        command:
          type: string
          enum:
            - firewall
            - install
            - local_volume
            - prune
            - swarm
    instance: "{{ docker }}"

- include_tasks: '{{ docker.command }}.yml'
