---

- validate:
    schema:
      type: object
      properties:
        command:
          type: string
          enum:
            - bridge_network
            - dependency
            - install
            - prune_images
            - swarm
    instance: "{{ docker }}"

- include_tasks: '{{ docker.command }}.yml'
  when: docker.command is not 'dependency'