---

- validate:
    schema:
      type: object
      properties:
        command:
          type: string
          enum:
            - bridge_network
            - download_tls_keys
            - dependency
            - install
            - local_volume_from_device
            - prune_images
            - swarm
      required:
        - command
    instance: "{{ docker }}"

- include_tasks: '{{ docker.command }}.yml'
  when: docker.command != 'dependency'