---

- block:
    - validate:
        schema:
          type: object
          properties:
            manager_host:
              type: string
              format: hostname
            manager_port:
              type: integer
              default: 2377
              minimum: 1
              maximum: 65535
            state:
              type: string
              enum:
                - absent
                - present
              default: present
            token:
              type: string
          required:
            - manager_host
            - manager_port
            - state
            - token
        instance: "{{ docker }}"
      register: docker_validated

    - set_fact:
        docker_v: "{{ docker_validated.result }}"

    - name: "Get swarm status"
      command: docker info
      changed_when: no
      register: docker_swarm_return

    - name: "Join the swarm"
      command: "docker swarm join --token {{ docker_v.token }} {{docker_v.manager_host}}:{{ docker_v.manager_port }}"
      when:
        - docker_v.state == 'present'
        - "'Swarm: inactive' in docker_swarm_return.stdout"

    - name: "Leave the swarm"
      command: "docker swarm leave"
      when:
        - docker_v.state == 'absent'
        - "'Swarm: active' in docker_swarm_return.stdout"
  tags:
    - docker_swarm_node
