---

- validate:
    schema:
      type: object
      properties:
        host:
          oneOf:
            - type: string
              format: hostname
            - type: string
              format: ipv4
        port:
          type: integer
          default: 2377
        state:
          type: string
          enum:
            - absent
            - present
          default: present
        token:
          type: string
    instance: "{{ docker }}"
  register: docker_validated

- set_fact:
    docker_v: "{{ docker_validated.result }}"

- name: "Get swarm status"
  command: docker info
  changed_when: no
  register: docker_swarm_return

- debug:
    var: docker_v

- name: "Join the swarm"
  command: "docker swarm join --token {{ docker_v.token }} {{docker_v.host}}:{{ docker_v.port }}"
  when:
    - docker_v.state == 'present'
    - '"Swarm: inactive" in docker_swarm_return.stdout'

- name: "Leave the swarm"
  command: "docker swarm leave"
  when:
    - docker_v.state == 'absent'
    - '"Swarm: active" in docker_swarm_return.stdout'
